# Generated by Django 5.2.6 on 2025-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='safety_threshold',
            new_name='safe_threshold',
        ),
        migrations.AddField(
            model_name='event',
            name='crowded_threshold',
            field=models.IntegerField(default=1000),
        ),
    ]
