# Generated by Django 5.2.6 on 2025-09-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_alert_event_alter_event_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='headcountsnapshot',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Headcount Snapshot', 'verbose_name_plural': 'Headcount Snapshots'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='safe_threshold',
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Human-readable location (city/venue).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='User who manages this event (can acknowledge alerts / edit event).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='headcountsnapshot',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('qr', 'QR'), ('ml', 'ML')], default='qr', max_length=10),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['event', 'created_at'], name='core_alert_event_i_b3f393_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='core_alert_alert_t_0c2086_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['qr_token'], name='core_event_qr_toke_ae66db_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='core_event_locatio_5d3252_idx'),
        ),
        migrations.AddIndex(
            model_name='headcountsnapshot',
            index=models.Index(fields=['event', 'timestamp'], name='core_headco_event_i_f03d1b_idx'),
        ),
    ]
