# Generated by Django 5.2.6 on 2025-09-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_alert_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='safe_threshold',
            field=models.IntegerField(default=500, help_text='Legacy field name; prefer safety_threshold in code.'),
        ),
    ]
